"""Frozen Binance Spot USDT crypto scope selected by the 2026-07-21 study.

This is an input boundary for the relationship monitor, not a live market-universe
refresh. Updating it requires an explicit product change and does not rewrite the
research snapshot that supplied the original selection.
"""

UNIVERSE_SNAPSHOT_AT = "2026-07-21T06:42:30Z"
UNIVERSE_SOURCE_SHA256 = (
    "1f24adfb64b7a52a170b730ee7517916b2da8ab45785779dee6be991762186cc"
)

DEFAULT_SYMBOLS_CSV = (
    "0GUSDT,1000CATUSDT,1000CHEEMSUSDT,1000SATSUSDT,1INCHUSDT,"
    "1MBABYDOGEUSDT,2ZUSDT,AAVEUSDT,ACEUSDT,ACHUSDT,ACMUSDT,ACTUSDT,"
    "ACXUSDT,ADAUSDT,ADXUSDT,AEROUSDT,AEVOUSDT,AGLDUSDT,AIGENSYNUSDT,"
    "AIUSDT,AIXBTUSDT,ALGOUSDT,ALICEUSDT,ALLOUSDT,ALPINEUSDT,ALTUSDT,"
    "AMPUSDT,ANIMEUSDT,ANKRUSDT,APEUSDT,API3USDT,APTUSDT,ARBUSDT,"
    "ARKMUSDT,ARKUSDT,ARPAUSDT,ARUSDT,ASRUSDT,ASTERUSDT,ASTRUSDT,"
    "ATMUSDT,ATOMUSDT,ATUSDT,AUCTIONUSDT,AUDIOUSDT,AUSDT,AVAUSDT,"
    "AVAXUSDT,AVNTUSDT,AWEUSDT,AXLUSDT,AXSUSDT,BABYUSDT,BANANAS31USDT,"
    "BANANAUSDT,BANDUSDT,BANKUSDT,BARDUSDT,BARUSDT,BATUSDT,BBUSDT,"
    "BCHUSDT,BEAMXUSDT,BELUSDT,BERAUSDT,BFUSDUSDT,BICOUSDT,BIGTIMEUSDT,"
    "BIOUSDT,BLURUSDT,BMTUSDT,BNBUSDT,BNSOLUSDT,BNTUSDT,BOMEUSDT,"
    "BONKUSDT,BREVUSDT,BROCCOLI714USDT,BTCUSDT,BTTCUSDT,C98USDT,"
    "CAKEUSDT,CATIUSDT,CELOUSDT,CELRUSDT,CETUSUSDT,CFGUSDT,CFXUSDT,"
    "CGPTUSDT,CHIPUSDT,CHRUSDT,CHZUSDT,CITYUSDT,CKBUSDT,COMPUSDT,"
    "COOKIEUSDT,COTIUSDT,COWUSDT,CRVUSDT,CTKUSDT,CTSIUSDT,CUSDT,"
    "CVCUSDT,CVXUSDT,CYBERUSDT,DASHUSDT,DCRUSDT,DEXEUSDT,DGBUSDT,"
    "DIAUSDT,DODOUSDT,DOGEUSDT,DOGSUSDT,DOLOUSDT,DOTUSDT,DUSKUSDT,"
    "DYDXUSDT,DYMUSDT,EDENUSDT,EDUUSDT,EGLDUSDT,EIGENUSDT,ENAUSDT,"
    "ENJUSDT,ENSOUSDT,ENSUSDT,EPICUSDT,ERAUSDT,ESPUSDT,ETCUSDT,"
    "ETHFIUSDT,ETHUSDT,EULUSDT,FETUSDT,FFUSDT,FIDAUSDT,FILUSDT,"
    "FLOKIUSDT,FLOWUSDT,FLUXUSDT,FOGOUSDT,FORMUSDT,FRAXUSDT,FTTUSDT,"
    "FUSDT,GALAUSDT,GASUSDT,GENIUSUSDT,GIGGLEUSDT,GLMRUSDT,GLMUSDT,"
    "GMTUSDT,GMXUSDT,GNOUSDT,GNSUSDT,GPSUSDT,GRAMUSDT,GRTUSDT,GTCUSDT,"
    "GUNUSDT,GUSDT,HAEDALUSDT,HBARUSDT,HEIUSDT,HEMIUSDT,HFTUSDT,"
    "HIVEUSDT,HMSTRUSDT,HOLOUSDT,HOMEUSDT,HOTUSDT,HUMAUSDT,HYPERUSDT,"
    "ICPUSDT,ICXUSDT,IDUSDT,ILVUSDT,IMXUSDT,INITUSDT,INJUSDT,IOSTUSDT,"
    "IOTAUSDT,IOTXUSDT,IOUSDT,IQUSDT,JASMYUSDT,JOEUSDT,JSTUSDT,JTOUSDT,"
    "JUPUSDT,JUVUSDT,KAIAUSDT,KAITOUSDT,KATUSDT,KAVAUSDT,KERNELUSDT,"
    "KGSTUSDT,KITEUSDT,KMNOUSDT,KNCUSDT,KSMUSDT,LAUSDT,LAYERUSDT,"
    "LAZIOUSDT,LDOUSDT,LINEAUSDT,LINKUSDT,LISTAUSDT,LPTUSDT,LQTYUSDT,"
    "LSKUSDT,LTCUSDT,LUMIAUSDT,LUNAUSDT,LUNCUSDT,MAGICUSDT,MANAUSDT,"
    "MANTAUSDT,MANTRAUSDT,MASKUSDT,MAVUSDT,MBLUSDT,MEGAUSDT,MEMEUSDT,"
    "METISUSDT,METUSDT,MEUSDT,MINAUSDT,MIRAUSDT,MITOUSDT,MMTUSDT,"
    "MORPHOUSDT,MOVEUSDT,MOVRUSDT,MTLUSDT,MUBARAKUSDT,NEARUSDT,"
    "NEIROUSDT,NEOUSDT,NEWTUSDT,NEXOUSDT,NIGHTUSDT,NILUSDT,NMRUSDT,"
    "NOMUSDT,NOTUSDT,NXPCUSDT,OGNUSDT,OGUSDT,ONDOUSDT,ONEUSDT,ONGUSDT,"
    "ONTUSDT,OPENUSDT,OPGUSDT,OPNUSDT,OPUSDT,ORCAUSDT,ORDIUSDT,"
    "OSMOUSDT,PARTIUSDT,PENDLEUSDT,PENGUUSDT,PEOPLEUSDT,PEPEUSDT,"
    "PHAUSDT,PIVXUSDT,PIXELUSDT,PLUMEUSDT,PNUTUSDT,POLUSDT,POLYXUSDT,"
    "PORTALUSDT,PORTOUSDT,POWRUSDT,PROMUSDT,PROVEUSDT,PSGUSDT,PUMPUSDT,"
    "PUNDIXUSDT,PYRUSDT,PYTHUSDT,QIUSDT,QKCUSDT,QNTUSDT,QTUMUSDT,"
    "QUICKUSDT,RADUSDT,RAREUSDT,RAYUSDT,REDUSDT,RENDERUSDT,REQUSDT,"
    "RESOLVUSDT,REUSDT,REZUSDT,RIFUSDT,RLCUSDT,ROBOUSDT,RONINUSDT,"
    "ROSEUSDT,RPLUSDT,RSRUSDT,RUNEUSDT,RVNUSDT,SAGAUSDT,SAHARAUSDT,"
    "SANDUSDT,SANTOSUSDT,SAPIENUSDT,SCRTUSDT,SCRUSDT,SCUSDT,SEIUSDT,"
    "SENTUSDT,SFPUSDT,SHELLUSDT,SHIBUSDT,SIGNUSDT,SKLUSDT,SKYUSDT,"
    "SLPUSDT,SNXUSDT,SOLUSDT,SOLVUSDT,SOMIUSDT,SOPHUSDT,SPELLUSDT,"
    "SPKUSDT,SSVUSDT,STEEMUSDT,STGUSDT,STORJUSDT,STOUSDT,STRAXUSDT,"
    "STRKUSDT,STXUSDT,SUIUSDT,SUNUSDT,SUPERUSDT,SUSDT,SUSHIUSDT,"
    "SXTUSDT,SYNUSDT,SYRUPUSDT,TAOUSDT,TFUELUSDT,THETAUSDT,THEUSDT,"
    "TIAUSDT,TKOUSDT,TLMUSDT,TNSRUSDT,TOWNSUSDT,TRBUSDT,TREEUSDT,"
    "TRUMPUSDT,TRXUSDT,TSTUSDT,TURBOUSDT,TURTLEUSDT,TUSDT,TUTUSDT,"
    "TWTUSDT,UMAUSDT,UNIUSDT,USDEUSDT,USTCUSDT,USUALUSDT,VANAUSDT,"
    "VANRYUSDT,VELODROMEUSDT,VETUSDT,VICUSDT,VIRTUALUSDT,VTHOUSDT,"
    "WALUSDT,WAXPUSDT,WBETHUSDT,WBTCUSDT,WCTUSDT,WIFUSDT,WINUSDT,"
    "WLDUSDT,WLFIUSDT,WOOUSDT,WUSDT,XAIUSDT,XECUSDT,XLMUSDT,XNOUSDT,"
    "XPLUSDT,XRPUSDT,XTZUSDT,XUSDUSDT,XVGUSDT,XVSUSDT,YBUSDT,YFIUSDT,"
    "YGGUSDT,ZAMAUSDT,ZBTUSDT,ZECUSDT,ZENUSDT,ZILUSDT,ZKCUSDT,"
    "ZKPUSDT,ZKUSDT,ZROUSDT,ZRXUSDT,币安人生USDT"
)
DEFAULT_SYMBOLS = tuple(DEFAULT_SYMBOLS_CSV.split(","))

__all__ = [
    "DEFAULT_SYMBOLS",
    "UNIVERSE_SNAPSHOT_AT",
    "UNIVERSE_SOURCE_SHA256",
]
